### PR TITLE
Added readLine Test (needs review)

### PR DESCRIPTION
**Pull request by jessebarton**
Started a readLine Test, still having some issues with this though. Pretty sure that its mainly because i don't have a test log file that i can use or the test content i have so far is not correct.

Appreciate any help that can be provided.

### CODE REVIEW

**Comment by chrisvaughn** [comment]
thanks for taking a look at this Jesse. I need to generate a realistic logdna archive test file.  I think this will make a lot more sense once you can see the test file.  

The readLine method does 2 important things. 

1.  it takes a path to a gzipped logdna archive, opens it and streams it line by line (it doesn't ungzip the file first)
2. it parses each json line from the file to see if the "_app" element in the json matches one of the app names in the config, if so it sends the app name and the "_line" element of the log on a channel for the processLine step.

So for this test we need a test file that contains a few different logs from app we care about and apps we don't care about. Then the test needs to setup a config for the apps we care about and call readLine with the test file and then read the channel to make sure we get all the data we expect and no extra.

**Comment by chrisvaughn** [comment]
I'm attaching a test file I created.  You can unzip it to look at it but you'll need to keep it gzipped to test with.  You can create a new directory in the repo called `test_data` and drop this in.
[testlog.json.gz](https://github.com/lifechurch/dnaquery/files/1714855/testlog.json.gz)

In this file, you'll see 2 different apps `worker-production` and `ingress-lb`.  I think for the test of readLine you should create a config in code that defines 1 app `ingress-lb`.  You should be able to use that config to set up a DNA instance with something like 
```
	c1 := App{
		Name: "ingress-lb",
		Regex: `^.*$`
	}
	cfg := &Configuration{
		Apps: []App{c1},
		Storage: Storage{LogDirectory: "/tmp/"},
	}
	dna, err := NewDNAQuery(cfg)
```

and then call something `dna.readLine("test_data/testlog.json.gz")`  that call will give you back a channel that you can read from.  You should get 6 items on the channel since there are 6 logs in the test file from app `ingress-lb`.  If you can verify you get 6 items and they contain the right data AND that you only get 6 the main point of the test is accomplished.  After that, you can use code coverage to check for any error cases that might be testable.

I have a busy couple days coming up but I'm happy to talk this over in the office on Wed. Thanks again.

**Comment by jessebarton** [comment]
Great! Ill work on this and would love to chat about it a bit more. That gives me a good start at trying to figure this out.

**Comment by chrisvaughn** [comment]
Hi Jesse.  I'm about to submit another PR that adds this test.  I needed to get a test in place so that I could do a refactor. I'm going to close this PR and find a couple other things in the project that you can help out with. Please see https://github.com/lifechurch/dnaquery/pull/27 for how I added tests to this

**Comment by jessebarton** [comment]
Sounds good, looking forward to contributing more.

**Pull request closed without merging**
